version: '3'

services:
  
  # entry:
  #   build: ./service/application
  #   container_name: entry
  #   ports:
  #     - '3000:3000'
  #   expose:
  #     - '3000'
  #   networks:
  #     - psi

  # entry_nginx:
  #   build: ./service/proxy
  #   container_name: entry_nginx
  #   ports:
  #     - '3100:3100'
  #   expose:
  #     - '3100'
  #   networks:
  #     - psi
    
  entry_db:
    build: ./database
    container_name: entry_db
    ports:
      - '3200:27017'
    expose:
      - '3200'
    networks:
      - psi

networks:
  psi:
    external: true